name: google_maps_marker_widgets
description: A Flutter package for using widgets as markers in Google Maps.
repository: https://github.com/jbadger3/google_maps_marker_widgets
issue_tracker: https://github.com/jbadger3/google_maps_marker_widgets/issues?q=is%3Aissue+is%3Aopen
topics:
  - google-maps-flutter
  - map
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
